// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: user.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    hashed_password,
    expire_at
) VALUES (
    $1, $2, $3, $4
) RETURNING username, email, hashed_password, password_changed_at, created_at, expire_at
`

type CreateUserParams struct {
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashedPassword"`
	ExpireAt       time.Time `json:"expireAt"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.ExpireAt,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ExpireAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users 
WHERE username = $1
`

func (q *Queries) DeleteUser(ctx context.Context, username string) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, username)
	return err
}

const getUser = `-- name: GetUser :one
SELECT username, email, hashed_password, password_changed_at, created_at, expire_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ExpireAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT username, email, hashed_password, password_changed_at, created_at, expire_at FROM users
ORDER BY username
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Username,
			&i.Email,
			&i.HashedPassword,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.ExpireAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserExpireTime = `-- name: UpdateUserExpireTime :one
UPDATE users 
SET expire_at = $2
WHERE username= $1
RETURNING username, email, hashed_password, password_changed_at, created_at, expire_at
`

type UpdateUserExpireTimeParams struct {
	Username string    `json:"username"`
	ExpireAt time.Time `json:"expireAt"`
}

func (q *Queries) UpdateUserExpireTime(ctx context.Context, arg UpdateUserExpireTimeParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserExpireTimeStmt, updateUserExpireTime, arg.Username, arg.ExpireAt)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.ExpireAt,
	)
	return i, err
}
